### ISSUE TITLE
Конфликт с Jquery от других компонентов

### ISSUE THREAD

**Issue by alroniks** [createit-ru/Mapex2#2]
В частности не работает с установленным ContentBlocks. Нужно вызывать jQuery не явно, а использовать noConflict() функцию

**Comment by alroniks** [comment]
Решилось добавление кода
`var $ = jQuery.noConflict();` в mapex.init.js
Но нужно протестировать другие случаи

**Comment by createit-ru** [comment]
https://github.com/createit-ru/Mapex2/commit/0f821435099041c77b12b364116e3fb68dd3a676
